In [ ]:
! pip install word2number

Requirement already satisfied: word2number in /usr/local/lib/python3.10/dist-packages (1.1)

In [ ]:
import numpy as np
import pandas as pd
from word2number import w2n
from sklearn.model_selection import train_test_split, GridSearchCV
import matplotlib.pyplot as plt
from sklearn import metrics

In [ ]:
data = pd.read_csv("/content/Clean_Dataset.csv", nrows = 1000)

data.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   airline           1000 non-null   object
 2   flight            1000 non-null   object
 3   source_city       1000 non-null   object
 4   departure_time    1000 non-null   object
 5   stops             1000 non-null   object
 6   arrival_time      1000 non-null   object
 7   destination_city  1000 non-null   object
 8   class             1000 non-null   object
 9   duration          1000 non-null   float64
 10  days_left         1000 non-null   int64
 11  price             1000 non-null   int64
dtypes: float64(1), int64(3), object(8)
memory usage: 93.9+ KB

In [ ]:
data = data.drop('flight', axis=1)

In [ ]:
data = data.drop('Unnamed: 0', axis=1)

In [ ]:
print(data)

       airline source_city departure_time stops   arrival_time  \
0     SpiceJet       Delhi        Evening  zero          Night
1     SpiceJet       Delhi  Early_Morning  zero        Morning
2      AirAsia       Delhi  Early_Morning  zero  Early_Morning
3      Vistara       Delhi        Morning  zero      Afternoon
4      Vistara       Delhi        Morning  zero        Morning
..         ...         ...            ...   ...            ...
995  Air_India       Delhi  Early_Morning   one          Night
996  Air_India       Delhi        Evening   one      Afternoon
997     Indigo       Delhi          Night   one        Morning
998  Air_India       Delhi        Evening   one          Night
999     Indigo       Delhi        Evening   one          Night

    destination_city    class  duration  days_left  price
0             Mumbai  Economy      2.17          1   5953
1             Mumbai  Economy      2.33          1   5953
2             Mumbai  Economy      2.17          1   5956
3             Mumbai  Economy      2.25          1   5955
4             Mumbai  Economy      2.33          1   5955
..               ...      ...       ...        ...    ...
995           Mumbai  Economy     17.83          7   9000
996           Mumbai  Economy     20.83          7   9053
997           Mumbai  Economy     10.42          7   9263
998           Mumbai  Economy     24.75          7   9315
999           Mumbai  Economy      4.42          7   9373

[1000 rows x 10 columns]

In [ ]:
data.isnull().sum()

airline             0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [ ]:
for i in range(len(data)):
  if data['stops'][i] == 'two_or_more':
    data['stops'][i] =2
  else:
    data['stops'][i] =w2n.word_to_num(data['stops'][i])

<ipython-input-181-ecc9acf38e24>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['stops'][i] =w2n.word_to_num(data['stops'][i])
<ipython-input-181-ecc9acf38e24>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['stops'][i] =2

In [ ]:
pred_data = data

In [ ]:
data.head()

,airline,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,Delhi,Evening,0,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,Delhi,Early_Morning,0,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,Delhi,Early_Morning,0,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,Delhi,Morning,0,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,Delhi,Morning,0,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
categorical_columns = ['airline', 'source_city', 'departure_time', 'arrival_time', 'destination_city', 'class']
data_encoded = pd.get_dummies(data, columns=categorical_columns)
print(data_encoded)
print(data_encoded.columns)

    stops  duration  days_left  price  airline_AirAsia  airline_Air_India  \
0       0      2.17          1   5953                0                  0
1       0      2.33          1   5953                0                  0
2       0      2.17          1   5956                1                  0
3       0      2.25          1   5955                0                  0
4       0      2.33          1   5955                0                  0
..    ...       ...        ...    ...              ...                ...
995     1     17.83          7   9000                0                  1
996     1     20.83          7   9053                0                  1
997     1     10.42          7   9263                0                  0
998     1     24.75          7   9315                0                  1
999     1      4.42          7   9373                0                  0

     airline_GO_FIRST  airline_Indigo  airline_SpiceJet  airline_Vistara  ...  \
0                   0               0                 1                0  ...
1                   0               0                 1                0  ...
2                   0               0                 0                0  ...
3                   0               0                 0                1  ...
4                   0               0                 0                1  ...
..                ...             ...               ...              ...  ...
995                 0               0                 0                0  ...
996                 0               0                 0                0  ...
997                 0               1                 0                0  ...
998                 0               0                 0                0  ...
999                 0               1                 0                0  ...

     departure_time_Morning  departure_time_Night  arrival_time_Afternoon  \
0                         0                     0                       0
1                         0                     0                       0
2                         0                     0                       0
3                         1                     0                       1
4                         1                     0                       0
..                      ...                   ...                     ...
995                       0                     0                       0
996                       0                     0                       1
997                       0                     1                       0
998                       0                     0                       0
999                       0                     0                       0

     arrival_time_Early_Morning  arrival_time_Evening  \
0                             0                     0
1                             0                     0
2                             1                     0
3                             0                     0
4                             0                     0
..                          ...                   ...
995                           0                     0
996                           0                     0
997                           0                     0
998                           0                     0
999                           0                     0

     arrival_time_Late_Night  arrival_time_Morning  arrival_time_Night  \
0                          0                     0                   1
1                          0                     1                   0
2                          0                     0                   0
3                          0                     0                   0
4                          0                     1                   0
..                       ...                   ...                 ...
995                        0                     0                   1
996                        0                     0                   0
997                        0                     1                   0
998                        0                     0                   1
999                        0                     0                   1

     destination_city_Mumbai  class_Economy
0                          1              1
1                          1              1
2                          1              1
3                          1              1
4                          1              1
..                       ...            ...
995                        1              1
996                        1              1
997                        1              1
998                        1              1
999                        1              1

[1000 rows x 24 columns]
Index(['stops', 'duration', 'days_left', 'price', 'airline_AirAsia',
       'airline_Air_India', 'airline_GO_FIRST', 'airline_Indigo',
       'airline_SpiceJet', 'airline_Vistara', 'source_city_Delhi',
       'departure_time_Afternoon', 'departure_time_Early_Morning',
       'departure_time_Evening', 'departure_time_Morning',
       'departure_time_Night', 'arrival_time_Afternoon',
       'arrival_time_Early_Morning', 'arrival_time_Evening',
       'arrival_time_Late_Night', 'arrival_time_Morning', 'arrival_time_Night',
       'destination_city_Mumbai', 'class_Economy'],
      dtype='object')

In [ ]:
data_encoded.head()

,stops,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,...,departure_time_Morning,departure_time_Night,arrival_time_Afternoon,arrival_time_Early_Morning,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night,destination_city_Mumbai,class_Economy
0,0,2.17,1,5953,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,1,1
1,0,2.33,1,5953,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,1
2,0,2.17,1,5956,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,1
3,0,2.25,1,5955,0,0,0,0,0,1,...,1,0,1,0,0,0,0,0,1,1
4,0,2.33,1,5955,0,0,0,0,0,1,...,1,0,0,0,0,0,1,0,1,1

In [ ]:
X=data_encoded[data_encoded.columns[~data_encoded.columns.isin(['price'])]]

y=data_encoded['price']

In [ ]:
X_train,X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

linear = LinearRegression()

linear.fit(X_train, y_train)

LinearRegression()

In [ ]:
pred=linear.predict(X_train)

In [ ]:
from sklearn.metrics import r2_score
score = r2_score(y_train, pred)
print("The training r2-Score of linear model is {}%".format(round(score, 2) *100))

linear.score(X_train, y_train)

The training r2-Score of linear model is 51.0%

0.5103850899618747

In [ ]:
score_test = r2_score(X_test, y_test)
print("The test r2-Score of linear model is {}%".format(round(score_test, 2) *100))

linear.score(X_test, y_test)

ValueError: ignored

SVR

In [ ]:
from sklearn.svm import SVR
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as  plt

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
hyper_param_svr = {
    'kernel': ['linear', 'rbf', 'poly'],
    'C': [1, 5, 10, 100],
    'gamma': ['scale', 'auto']
}

In [ ]:
svr = SVR()

In [ ]:
grid_search = GridSearchCV(estimator=svr, param_grid=hyper_param_svr, cv=5, scoring='neg_mean_squared_error', verbose=1, n_jobs=-1)
grid_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

In [ ]:
best_params_svr = grid_search.best_params_
best_estimator_svr = grid_search.best_estimator_

print("Best Parameters for SVR:", best_params_svr)

In [ ]:
svr_pred = best_estimator_svr.predict(X_test_scaled)

In [ ]:
svr_score_train = best_estimator_svr.score(X_train_scaled, y_train)

print("The training r2-Score of SVR model is {}%".format(round(svr_score_train, 2) *100))

In [ ]:
svr_score_test = best_estimator_svr.score(X_test_scaled, y_test)

print("The test r2-Score of SVR model is {}%".format(round(svr_score_test, 2) *100))

Random Forest Regressor

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.preprocessing import LabelEncoder

In [ ]:
random_forest = RandomForestRegressor()

In [ ]:
hyper_param_RForest = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [ ]:
grid_search_r = GridSearchCV(estimator=random_forest, param_grid=hyper_param_RForest, cv=5, scoring='neg_mean_squared_error', verbose=1, n_jobs=-1)
grid_search_r.fit(X_train, y_train)

In [ ]:
best_params_r = grid_search_r.best_params_
best_estimator_r = grid_search_r.best_estimator_

print("Best Parameters for Random Forest Regressor:", best_params_r)

In [ ]:
for_pred = best_estimator_r.predict(X_test)

In [ ]:
forest_score_train = best_estimator_r.score(X_train, y_train)

print("The training r2-Score of Random Forest Regressor model is {}%".format(round(forest_score_train, 2) *100))

In [ ]:
forest_score_test = best_estimator_r.score(X_test, y_test)

print("The test r2-Score of Random Forest Regressor model is {}%".format(round(forest_score_test, 2) *100))

XGBoost

In [ ]:
from xgboost import XGBRegressor

In [ ]:
xgb_reg = XGBRegressor()

In [ ]:
xgb_reg.fit(X_train, y_train)

y_pred = xgb_reg.predict(X_test)

ValueError: ignored

In [ ]:
test = pd.DataFrame({
    'airline': ['SpiceJet'],
    'source_city': ['Delhi'],
    'departure_time': ['Evening'],
    'stops': ['zero'],
    'arrival_time': ['Night'],
    'destination_city': ['Mumbai'],
    'class': ['Economy'],
    'duration': [2.17],
    'days_left': [1]
})

In [ ]:
pred_data=pred_data.append({
    'airline': 'SpiceJet',
    'source_city':'Delhi',
    'departure_time': 'Evening',
    'stops': 1,
    'arrival_time': 'Night',
    'destination_city': 'Mumbai',
    'class': 'Economy',
    'duration': 2.17,
    'days_left': 1
},ignore_index=True)

<ipython-input-191-ad162b942012>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pred_data=pred_data.append({

In [ ]:
print(pred_data)

        airline source_city departure_time stops   arrival_time  \
0      SpiceJet       Delhi        Evening     0          Night
1      SpiceJet       Delhi  Early_Morning     0        Morning
2       AirAsia       Delhi  Early_Morning     0  Early_Morning
3       Vistara       Delhi        Morning     0      Afternoon
4       Vistara       Delhi        Morning     0        Morning
...         ...         ...            ...   ...            ...
996   Air_India       Delhi        Evening     1      Afternoon
997      Indigo       Delhi          Night     1        Morning
998   Air_India       Delhi        Evening     1          Night
999      Indigo       Delhi        Evening     1          Night
1000   SpiceJet       Delhi        Evening     1          Night

     destination_city    class  duration  days_left   price
0              Mumbai  Economy      2.17          1  5953.0
1              Mumbai  Economy      2.33          1  5953.0
2              Mumbai  Economy      2.17          1  5956.0
3              Mumbai  Economy      2.25          1  5955.0
4              Mumbai  Economy      2.33          1  5955.0
...               ...      ...       ...        ...     ...
996            Mumbai  Economy     20.83          7  9053.0
997            Mumbai  Economy     10.42          7  9263.0
998            Mumbai  Economy     24.75          7  9315.0
999            Mumbai  Economy      4.42          7  9373.0
1000           Mumbai  Economy      2.17          1     NaN

[1001 rows x 10 columns]

In [ ]:
print(pred_data)

        airline source_city departure_time stops   arrival_time  \
0      SpiceJet       Delhi        Evening     0          Night
1      SpiceJet       Delhi  Early_Morning     0        Morning
2       AirAsia       Delhi  Early_Morning     0  Early_Morning
3       Vistara       Delhi        Morning     0      Afternoon
4       Vistara       Delhi        Morning     0        Morning
...         ...         ...            ...   ...            ...
996   Air_India       Delhi        Evening     1      Afternoon
997      Indigo       Delhi          Night     1        Morning
998   Air_India       Delhi        Evening     1          Night
999      Indigo       Delhi        Evening     1          Night
1000   SpiceJet       Delhi        Evening     1          Night

     destination_city    class  duration  days_left   price
0              Mumbai  Economy      2.17          1  5953.0
1              Mumbai  Economy      2.33          1  5953.0
2              Mumbai  Economy      2.17          1  5956.0
3              Mumbai  Economy      2.25          1  5955.0
4              Mumbai  Economy      2.33          1  5955.0
...               ...      ...       ...        ...     ...
996            Mumbai  Economy     20.83          7  9053.0
997            Mumbai  Economy     10.42          7  9263.0
998            Mumbai  Economy     24.75          7  9315.0
999            Mumbai  Economy      4.42          7  9373.0
1000           Mumbai  Economy      2.17          1     NaN

[1001 rows x 10 columns]

In [ ]:
pred_data.isnull().sum()

airline             0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               1
dtype: int64

In [ ]:
categorical_columns = ['airline', 'source_city', 'departure_time', 'arrival_time', 'destination_city', 'class']
test_encoded = pd.get_dummies(pred_data, columns=categorical_columns)
print(test_encoded)
print(test_encoded.columns)

     stops  duration  days_left   price  airline_AirAsia  airline_Air_India  \
0        0      2.17          1  5953.0                0                  0
1        0      2.33          1  5953.0                0                  0
2        0      2.17          1  5956.0                1                  0
3        0      2.25          1  5955.0                0                  0
4        0      2.33          1  5955.0                0                  0
...    ...       ...        ...     ...              ...                ...
996      1     20.83          7  9053.0                0                  1
997      1     10.42          7  9263.0                0                  0
998      1     24.75          7  9315.0                0                  1
999      1      4.42          7  9373.0                0                  0
1000     1      2.17          1     NaN                0                  0

      airline_GO_FIRST  airline_Indigo  airline_SpiceJet  airline_Vistara  \
0                    0               0                 1                0
1                    0               0                 1                0
2                    0               0                 0                0
3                    0               0                 0                1
4                    0               0                 0                1
...                ...             ...               ...              ...
996                  0               0                 0                0
997                  0               1                 0                0
998                  0               0                 0                0
999                  0               1                 0                0
1000                 0               0                 1                0

      ...  departure_time_Morning  departure_time_Night  \
0     ...                       0                     0
1     ...                       0                     0
2     ...                       0                     0
3     ...                       1                     0
4     ...                       1                     0
...   ...                     ...                   ...
996   ...                       0                     0
997   ...                       0                     1
998   ...                       0                     0
999   ...                       0                     0
1000  ...                       0                     0

      arrival_time_Afternoon  arrival_time_Early_Morning  \
0                          0                           0
1                          0                           0
2                          0                           1
3                          1                           0
4                          0                           0
...                      ...                         ...
996                        1                           0
997                        0                           0
998                        0                           0
999                        0                           0
1000                       0                           0

      arrival_time_Evening  arrival_time_Late_Night  arrival_time_Morning  \
0                        0                        0                     0
1                        0                        0                     1
2                        0                        0                     0
3                        0                        0                     0
4                        0                        0                     1
...                    ...                      ...                   ...
996                      0                        0                     0
997                      0                        0                     1
998                      0                        0                     0
999                      0                        0                     0
1000                     0                        0                     0

      arrival_time_Night  destination_city_Mumbai  class_Economy
0                      1                        1              1
1                      0                        1              1
2                      0                        1              1
3                      0                        1              1
4                      0                        1              1
...                  ...                      ...            ...
996                    0                        1              1
997                    0                        1              1
998                    1                        1              1
999                    1                        1              1
1000                   1                        1              1

[1001 rows x 24 columns]
Index(['stops', 'duration', 'days_left', 'price', 'airline_AirAsia',
       'airline_Air_India', 'airline_GO_FIRST', 'airline_Indigo',
       'airline_SpiceJet', 'airline_Vistara', 'source_city_Delhi',
       'departure_time_Afternoon', 'departure_time_Early_Morning',
       'departure_time_Evening', 'departure_time_Morning',
       'departure_time_Night', 'arrival_time_Afternoon',
       'arrival_time_Early_Morning', 'arrival_time_Evening',
       'arrival_time_Late_Night', 'arrival_time_Morning', 'arrival_time_Night',
       'destination_city_Mumbai', 'class_Economy'],
      dtype='object')

In [ ]:
a=test_encoded[test_encoded.columns[~test_encoded.columns.isin(['price'])]]

b=test_encoded['price']

In [ ]:
a

,stops,duration,days_left,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,source_city_Delhi,...,departure_time_Morning,departure_time_Night,arrival_time_Afternoon,arrival_time_Early_Morning,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night,destination_city_Mumbai,class_Economy
0,0,2.17,1,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,1,1
1,0,2.33,1,0,0,0,0,1,0,1,...,0,0,0,0,0,0,1,0,1,1
2,0,2.17,1,1,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,1,1
3,0,2.25,1,0,0,0,0,0,1,1,...,1,0,1,0,0,0,0,0,1,1
4,0,2.33,1,0,0,0,0,0,1,1,...,1,0,0,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,1,20.83,7,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,0,1,1
997,1,10.42,7,0,0,0,1,0,0,1,...,0,1,0,0,0,0,1,0,1,1
998,1,24.75,7,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,1
999,1,4.42,7,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,1,1
1000,1,2.17,1,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,1,1,1

In [ ]:
b

0       5953.0
1       5953.0
2       5956.0
3       5955.0
4       5955.0
         ...
996     9053.0
997     9263.0
998     9315.0
999     9373.0
1000       NaN
Name: price, Length: 1001, dtype: float64

In [ ]:
l = a.iloc[-1]

In [ ]:
l.head()

stops                   1
duration             2.17
days_left               1
airline_AirAsia         0
airline_Air_India       0
Name: 1000, dtype: object

In [ ]:
linear.predict(l)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: ignored